### ISSUE TITLE
Criar cartões de vitória

### ISSUE THREAD

**Issue by victorl2** [victorl2/Guerra#2]
Criar a classe que representa os cartões de vitória, assim como seu componente visual.

**Vitórias:**
+ Entre todo mundo _( conquistar todas as áreas em azul claro )_
+ Bem no meio _(conquistar o centro da cidade  áreas azul+ roxo )_
+ Pelas Beiradas _( conquistas as áreas vermelha e amarela )_
+ Muitos territórios _( conquistar 20 territórios )_

Crie um cartão para da vitória, facilite a implementação dos componentes lógicos.

**Comment by lbpo91** [comment]
Componente visual já criado
